# Generated by Django 4.0.6 on 2022-07-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('president', models.CharField(max_length=120)),
                ('coach', models.CharField(max_length=130)),
                ('year', models.DateField()),
                ('davlat', models.CharField(max_length=100, null=True)),
                ('max_purchase', models.SmallIntegerField()),
                ('max_sell', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mamlakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('club_from', models.CharField(max_length=30)),
                ('club_to', models.CharField(max_length=30)),
                ('fee_pre', models.SmallIntegerField()),
                ('fee_real', models.SmallIntegerField()),
                ('season', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('yosh', models.SmallIntegerField()),
                ('davlat', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=120)),
                ('transfer_real', models.SmallIntegerField(null=True)),
                ('transfer_pre', models.SmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footapp.clubs')),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='mamlakat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footapp.mamlakat'),
        ),
    ]
