# Generated by Django 4.0.6 on 2022-07-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='davlat',
        ),
        migrations.RemoveField(
            model_name='players',
            name='transfer_pre',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='name',
        ),
        migrations.AddField(
            model_name='transfer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footapp.players'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='club_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_cl', to='footapp.clubs'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='club_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cl', to='footapp.clubs'),
        ),
    ]
